### ISSUE TITLE
Firefox simple-storage keeps getting trashed

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1893]
also it has a small quota

**Comment by ThiefMaster** [comment]
Not sure if it's related, but whenever my Firefox freezes for some reason and I kill it via Task Manager (last time it happened due to me leaving the steam minigame open for an hour or two), **all** RES data goes down the drain. Luckily I could copy it over from another PC, but it would be nice if RES backed up its data automatically, prompting to restore a backup if the main data is damaged/lost.

**Comment by honestbleeps** [comment]
it's absolutely related and this is the top cause of Firefox trashing RES's data.

I am against writing a backup system for two reasons:

1) We're looking at moving toward a new storage method which should erase this problem anyway

2) it's a ton of firefox specific code (writing files to hard drive is not really permitted in any other browser!) and is prone to errors/issues with testing, all due to a bug that's firefox's in the first place.  rather, we will focus on #1.
