### ISSUE TITLE
Can't change modmail keyboard shortcut in RES settings

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1954]
https://www.reddit.com/r/RESissues/comments/2r4g6m/bug_sourcesnudown_shows_gt_instead_of/

**Comment by erikdesjardins** [comment]
I think this has something to do with the option being called modmail (as opposed to it being implemented incorrectly/differently), since it works if you change the option's name to modmailTest.

But for the life of me, I can't find anything that would be conflicting (i.e. another option called modmail, another module accessing `modules['keyboardNav'].options.modmail`, etc.)

Although it's probably something really minor that I've overlooked.

**Comment by andytuba** [comment]
[2:10pm] <erikdesjardins>  
so I discovered why we can't save the modmail shortcut - we use .getElementById(optionKey) to update the hidden input that holds the keycode, but there's already a #modmail in moderators' userbars

[2:10pm] <erikdesjardins>  
right here https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/settingsConsole.js#L99
