### ISSUE TITLE
sourceSnudown shows &gt; for >

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1955]
https://www.reddit.com/r/RESissues/comments/2r4g6m/bug_sourcesnudown_shows_gt_instead_of/
When the data comes back from reddit, it uses &amp;gt; instead of >

I think sourceSnudown used .safeHtml before and I took that out because whatever, it's just text getting dumped into a textarea..  so this deserves a little research

**Comment by andytuba** [comment]
(repro'd in osx chrome canary v41)

**Comment by erikdesjardins** [comment]
Reproduced in Win 8.1 Chrome 39

We stopped using `.safeHtml` because it trims off whitespace at the beginning. (#1839 - and now I notice that I cloned `userTextForm`, whoops)

It seems that out of all of these characters:

    < > & ` ~ ! @ # $ % * ( ) _ + - = [ ] { } \ | ; ' : " , . / ? ^
    ¡ ¢ £ ¤ ¥ ¦ § ¨ © ª « ¬ ® ¯ ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ × ÷ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö Ø Ù Ú Û Ü Ý Þ ß à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ø ù ú û ü ý þ ÿ

Only `< > &` remain escaped.

(I suppose we could just `.replace` them, but it wouldn't be very elegant)

**Comment by mc10** [comment]
We do have `escapeLookups` already, so we could just use the reverse of that object.
