### ISSUE TITLE
Google Maps expandos

### ISSUE THREAD

**Issue by jeffzemla** [honestbleeps/Reddit-Enhancement-Suite#2042]
Google Maps allows embedding maps, satellite views, directions, street views, etc.

This would provide a huge usability improvement for subs such as /r/TakeOneStepForward, /r/FoundOnGoogleMaps, and /r/GoogleMaps

Unfortunately, documentation is sparse on how to convert a "New" Google Maps URL to an embedded URL. Iframely seems to work for regular links, but does not work for street views.

**Comment by honestbleeps** [comment]
it has been a while since I've worked with the google maps API, but back when I did I recall there being some pretty strict API limits, etc, unless you pay. There might be some serious hurdles here.

That said, if someone wants to jump in and work on this feature as long as they research those limits, I'm certainly supportive of that.  Not sure how high the core devteam would prioritize this due to its niche appeal, though.

**Comment by jeffzemla** [comment]
I don't believe there are usage limits for embedding maps.

> There are no usage limits for the Maps Embed API. You can embed maps or Street View panoramas on your high-traffic websites without fear of hitting a usage cap or query-per-second throttling.

https://developers.google.com/maps/documentation/embed/guide

There are other variants that do have usage limits, but they are not applicable here.

**Comment by honestbleeps** [comment]
good point, I was probably remembering limits around other functionality, thanks!
