### ISSUE TITLE
Filtering subreddit via the widget card doesn't work

### ISSUE THREAD

**Issue by Dashed** [honestbleeps/Reddit-Enhancement-Suite#2145]
Using master: https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/7a803d3e8959f47dd07074bdd52291ca878c0f35

------

Steps:

1. Go to reddit.com
2. Filter subreddit via its widget card (unsure what this is called): ![screen shot 2015-03-29 at 4 31 15 pm](https://cloud.githubusercontent.com/assets/139499/6887589/33094cf6-d632-11e4-9977-d44d4ad6d20f.png)
3. Verify it's added https://www.reddit.com/#!settings/filteReddit
4. Refresh reddit.com tab
5. Filtered subreddit not added to https://www.reddit.com/#!settings/filteReddit and thus not filtered.

-----

What does work is that once the subreddit is added; one can pop open the RES dashboard console and click "Save Options".

-----

@andytuba this seems to be a regression due to how changes are detected

**Comment by andytuba** [comment]
> widget card

heh, we don't really have a good name for it.. I usually call it "subreddit info hover pop-up."

---

Thanks for reporting it!  That would've annoyed a lot of people and I bet it wouldn't have been reported in time for the first hotfix..

If you're curious, the problem was that filteReddit's "save updated settings after adding/removing a filtered subreddit" call was bugged.. probably copy-pasta error somewhere recently.

**Comment by Dashed** [comment]
@andytuba Awesome! Updated and can confirm it's fixed.
