### ISSUE TITLE
Never Ending Reddit does not seem to load when browsing www.{locale}.reddit.com

### ISSUE THREAD

**Issue by himmelarthur** [honestbleeps/Reddit-Enhancement-Suite#2165]
The issue happens on Chrome v41 - OSX 64bit.
When browsing a localized version of reddit, e.g `www.fr.reddit.com`, NER cannot load page 2 :
> Next page URL mismatch. Something strange may be afoot.

This seems to be due to [this line](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/neverEndingReddit.js#L425) : `location.hostname` is `www.fr.reddit.com`; `me.nextPageURL` is `"http://fr.reddit.com/?count=25"` (`www.` is missing)

**Comment by allthefoxes** [comment]
Well, maybe I am wrong, but you should not be using www.locale.reddit.com - You should be using locale.reddit.com

Using www.locale.reddit.com messes with HTTPS as well.

**Comment by erikdesjardins** [comment]
I think this is more of a "you're not supposed to have both `www.` and a locale subdomain" issue rather than a RES issue, especially given that:

reddit tries to redirect you back to just `fr.reddit.com` if you click on the next arrow (causing this issue)
![capture](https://cloud.githubusercontent.com/assets/7673145/7013475/7d62b3fe-dc87-11e4-806e-3549d7c9d609.PNG)
And I can't even connect to `https://www.fr.reddit.com`, since their cert is only valid for `*.reddit.com`
![image](https://cloud.githubusercontent.com/assets/7673145/7013502/b56e0906-dc87-11e4-803f-cca980aaf37c.png)

**Comment by allthefoxes** [comment]
^

I can't even make a secure connection into www.locale.reddit.com - 

I suggest sticking to locale.reddit.com

**Comment by himmelarthur** [comment]
I guess you are totally right ! Not really a bug then, thank you for your time!

**Comment by andytuba** [comment]
@himmelarthur this is the part where you close the issue :grinning:

**Comment by andytuba** [comment]
also, if you stay logged in, you can set your reddit preferences to always show in French unless you specifically visit https://en.reddit.com/ or something
