### ISSUE TITLE
Firefox Addon - Conflict with RAS - Random Agent Spoofer

### ISSUE THREAD

**Issue by jamesdwilson** [honestbleeps/Reddit-Enhancement-Suite#2172]
Not sure if the issue is with RES or RAS, so I am opening an issue on each.

When RAS is enabled, RES does not load.

https://github.com/dillbyrne/random-agent-spoofer/

**Comment by andytuba** [comment]
I installed RAS and RES v4.5.4, then set RAS to load a random profile.  Seems to work fine.  Can you give any more details? Any errors from the webdev console? Your browser and RES version #s?

**Comment by jamesdwilson** [comment]
Figured out it is an issue with RES not working if "Disable local dom storage" is checked. Still a conflict. Still need a way to let these both work at the same time. I guess whitelist is my only option at this stage?
Ideally I don't have to lose my privacy gained from RAS for this.

**Comment by jamesdwilson** [comment]
Firefox 37. 
RES 4.5.4
RAS 0.9.5 (From github)

**Comment by honestbleeps** [comment]
DOM storage is what RES uses to store data. It simply will not work without it right now, sorry.

We're investigating new manners of data storage because of this bug, though, which may help (I'm not sure if DOM storage would affect an alternative such as indexedb, for example):

https://bugzilla.mozilla.org/show_bug.cgi?id=1091244

**Comment by jamesdwilson** [comment]
https://github.com/dillbyrne/random-agent-spoofer/issues/175
