### ISSUE TITLE
RES interacting strangely with /r/keys

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2219]
https://www.reddit.com/r/RESissues/comments/350nh4/bug_post_titles_from_rkeys_seem_to_have_some_text/

https://www.reddit.com/r/keys+randomprecision1

Also, /r/keys does not exist according to subredditHover

**Comment by jsayol** [comment]
This happens when the subreddit name coincides with a function in ```Array.prototype```. I did some testing and you can see the same behaviour with subreddits like [map](https://www.reddit.com/r/map+randomprecision1) or [sort](https://www.reddit.com/r/sort+randomprecision1).

The fix is easy: instead of using object[element] [here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/389d54cb0cc8d08db7668e0eb6604e049c920794/lib/modules/subredditTagger.js#L87-L88) to check if an element exists, just use object.hasOwnProperty(element).

I'm creating the pull request now.
