### ISSUE TITLE
Add module's short description to title in settings console left navbar

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2229]
The "short description" is the first sentence or paragraph, same as what search results should show.  make sure to plaintext it (no markdown or html)

**Comment by dhensche** [comment]
Is this a request to add this description to the title attribute of the li element in the navbar so that it shows on hover? 
Is it also desirable to show the full description like in search results (just escaping the HTML)?

**Comment by andytuba** [comment]
Title attribute could work. I was thinking more like a caption, for easy scanning.

How about full description (html stripped out) in the title, and first sentence as small text inside the li element?

**Comment by dhensche** [comment]
okay, I'll get something going tomorrow

**Comment by dhensche** [comment]
Okay, so the 'first sentence' part is a little bit trickier than I had expected 😄 . There are sort of 3 cases I need to deal with:

1. No tags in the description -- easiest because I can just take up to the first period
2. Description is completely enclosed in a tag -- I can wrap with jQuery and just fetch the text content and select up to the first period again
3. Description eventually has a tag -- select up to first tag and then within that text select up to first period?

Does this sound reasonable?

**Comment by andytuba** [comment]
Sorry, I saw your PR before your comment.

Yes, this approach sounds good 😄
