### ISSUE TITLE
Preview doesn't reflect the new r/ and u/  change

### ISSUE THREAD

**Issue by tankorsmash** [honestbleeps/Reddit-Enhancement-Suite#2329]
When you go to reply to a post and type in `r/subreddit`, it replaces it automatically with `/r/subreddit`, which is fine, but if you do want to type in `r/subreddit`, the preview doesn't render it as a link. 

This made sense, up until a few weeks ago when reddit made the change to support `u/user` and `r/subreddit`

**Comment by Antrikshy** [comment]
For anybody who decides to tackle, this one is tricky because RES uses [this library](https://github.com/gamefreak/snuownd) to parse Reddit's Markdown, which is a JavaScript port of [this parser](https://github.com/reddit/snudown). The latter has support for the no-leading-slashes case, but the JS port does not, *and* seems to be a dead project.

**Comment by erikdesjardins** [comment]
This is actually already fixed, because we switched to https://github.com/erikdesjardins/snudown-js a while ago.

**Comment by tankorsmash** [comment]
Thanks everyone!
