### ISSUE TITLE
Vote weights broken again

### ISSUE THREAD

**Issue by bpwned** [honestbleeps/Reddit-Enhancement-Suite#2486]
I've been using a self-built version of RES directly from this repository to get back the vote weights. Today I noticed that they don't work any more. I looked a bit through the code and found that the arrow class changed from upmod to up and from downmod to down, respectively (see https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/userTagger.js#L344). Changing RES to account for that did not restore the functionality. Unfortunately I'm not an extension developer so I don't have the tools to debug this further. Hence, I'm submitting this report.

**Comment by allthefoxes** [comment]
Can confirm.

Gif: http://i.imgur.com/N74aXuV.gifv

**Comment by erikdesjardins** [comment]
[This check](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/5cfde8ed62dd322e349de261e6856772574bd703/lib/modules/userTagger.js#L359) throws an error because arrows no longer have an `onclick` attribute.
It appears we can use the `.archived` class in its place.

I suspect that "hide arrows for archived posts" is also broken.

I'll fix this in a few days if I have time.

**Comment by withmorten** [comment]
Arrows for archived posts are visible, you are correct. I was wondering why they suddenly were.

Example archived post here: https://www.reddit.com/r/gallifrey/comments/2kbbun/doctor_who_8x10_in_the_forest_of_the_night/

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/RESissues/comments/3p7yky/bug_recent_reddit_change_on_voting_javascript/
