### ISSUE TITLE
Closing streamable expando does not pause

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2522]
https://www.reddit.com/r/RESissues/comments/3sv7j7/bug_collapse_of_streamablecom_videos_just_hides/

**Comment by tswaters** [comment]
Inside the streamable iframe, there is a listener that accepts play/pause requests - this raises an error `videojs is not defined`.  If this was changed to `player` it appears to work.  This is on streamable to fix; RES can't modify an iframe... it's already doing everything it can posting `{method: "pause"}` to the iframe.... streamable appears to recognize this but instead of pausing, it raises an error.

**Comment by andytuba** [comment]
Thanks for investigating that. I'll reach out to streamable support

**Comment by andytuba** [comment]
Appears to be fixed on Streamable's side.
