### ISSUE TITLE
Release branching scheme and tools

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2549]
http://nvie.com/posts/a-successful-git-branching-model/

but keep Reddit-Enhancement-Suite/master as the "develop/nightly" branch
and add Reddit-Enhancement-Suite/releases as the "master/production" branch
## 

Release workflow:
1. `gulp prep-release` 
2. Last-minute fixes committed directly to newly created release branch
3. `gulp release`

Hotfix release workflow:
1. `gulp prep-release -h`
2. `gulp release`

if somebody already wrote a PR for the hotfix
1. `gulp prep-release -h 1234`
2. `gulp release`

---

Gulp commands:

`gulp prep-release` 
- `git checkout master && git checkout -b release-4.A` where , if package.json version is currently `4.X` or `4.X.Y`, `A=X+1`
-  `gulp set-version -v 4.A`

`gulp prep-release -h [PR#]` # Start a hotfix release or turn a PR into a hotfix
- `git checkout $latest_release_branch or master`
- set version = `hotfix-4.X.A` where, if package.json version is currently `4.X` then `A=1` or if `4.X.Y` then `A=Y+1`
- if PR `git fetch origin pull/PR/head:hotfix-$version` else `git checkout master && git checkout -b hotfix-$version`
- `gulp set-version -v $version`    -- hmm,  

`gulp set-version -v foo [-f]` 
- updates package.json with given version
- git reset && git add package.json
- if -f (fixup) git commit -m 'Folded hotfix into release' else git commit -m Update version number'

`gulp release` 
- If $latest_hotfix_branch exists and $latest_release_branch exists and $latest_hotfix_branch is not yet merged into $latest_release_branch
  - git checkout $latest_release_branch
  - git merge --no-ff $latest_hotfix_branch
  - gulp set-version -v $latest_release_version -f
  - Fire warning "$latest_hotfix_branch merged, run `gulp release` again to release $latest_release_branch"
- else if $latest_hotfix_branch exists and $latest_release_branch does not exist
  - git checkout releases
  - git merge --no-ff $latest_hotfix_branch
  - gulp package (build and zip or whatever)
  - gulp post-release
- else if $latest_release_branch exists
  - git checkout releases
  - git merge --no-ff $latest_release_branch
  - gulp package (build and zip or whatever)
  - gulp post-release

`gulp post-release -h` (only run when a hotfix was merged into a release branch but is needed in development before release branch is merged)
- git checkout master
- git merge --no-f $latest_hotfix_branch
- if $latest_hotfix_branch exists and $latest_release_branch exists and $latest_hotfix_branch is merged into $latest_release_branch, `git branch -d $latest_hotfix_branch`, 
- git checkout master; git merge --no-f $latest_release_branch && git branch -d $latest_release_branch

**Comment by mc10** [comment]
Sounds good! Some minor things:
* I think it makes more sense to call the branch `release` (without the s).
* Version hotfixes should probably just increment the last number instead of adding a `-hotfix`; what if there are two or more?

**Comment by andytuba** [comment]
Plain release sounds great.

> Version hotfixes should probably just increment the last number instead of adding a -hotfix; what if there are two or more?

I'm thinking version numbers like:

4.6 - features and bugfixes
4.6.1 -- hotfix
4.6.2 -- hotfix 
4.6.3 -- hotfix
4.7.0 -- features and bugfixes
4.7.1 -- hotfix
etc.

so the hotfix branch names are hotfix-4.6.1, hotfix-4.7.2, etc. 

Did I understand your comment right?

**Comment by mc10** [comment]
Works for me.

**Comment by xiongchiamiov** [comment]
One thing about the original git-flow is that it's a bit overkill for most development; it has a bunch of stuff that's only necessary if you're supporting old releases.  However, RES isn't going to ship 4.6.2 after 4.7; there's just one current version in the store, so there's no need to backport fixes.

That kind of situation mostly works with the standard master branch approach (where feature branches get merged into master and releases are cut from there).  The main problem is when there's a fix that needs to go out quickly, but other things sitting in master prevent that.

The easiest way to solve that, I think is to have [a two-branch model](https://github.com/ifixit/git-scripts#branching-model).  The latest commit on `stable` is always what's been released to the store, while things that have been approved to go into the next release are in `master`.  Most of the time, you branch off of and merge into master, and when you want to release, you merge master into stable and cut the release.  When you need to push out a hotfix, though, you can branch off of and merge into stable, bypassing the commits sitting in master that may not be quite ready for a release yet.

And since you're not backporting patches for older versions, you can just use tags when you release instead of creating a bunch of branches that will be never touched.

**Comment by andytuba** [comment]
Two-branch sounds like good advice, simplest+sufficient, and my slavish attempt at vanilla gitflow is misguided as it is rather overblown.

My main interest in separate branches is to allow 4.7 (future major release) development to proceed, particularly with all the infrastructural changes recently merged to master, while providing a stableish branch for 4.6.0 (upcoming next release) and 4.6.x - subsequent hotfixes to that.

Sounds like I should rename the release/4.6.0 branch I've created to `stable` and leave `master` as-is. I feel a bit odd about using the name `stable` since it'll be a little rough at some given points.. 

:+1: on carrying on with tagging releases, instead of making/trashing release branches all the time.

**Comment by Ajedi32** [comment]
This should be moved to a new milestone. (Maybe v4.6.1?)

**Comment by xiongchiamiov** [comment]
> Sounds like I should rename the release/4.6.0 branch I've created to stable and leave master as-is. I feel a bit odd about using the name stable since it'll be a little rough at some given points..

Oh, my use of master/stable was just what we decided to use at a previous employer; devel/master is, I think, more common, and you can of course use whatever makes the most sense to you. :)

**Comment by mc10** [comment]
Our current scheme has been working reasonably; closing.
