### ISSUE TITLE
Invisible text in night mode

### ISSUE THREAD

**Issue by xrisk** [honestbleeps/Reddit-Enhancement-Suite#2586]
Award table on https://www.reddit.com/wiki/awards

**Comment by erikdesjardins** [comment]
Fixed in master and stable (release/4.6.0).
![image](https://cloud.githubusercontent.com/assets/7673145/12075505/3534a41c-b151-11e5-8335-0e58b683772d.png)
https://www.reddit.com/r/RESissues/wiki/knownissues#wiki_nightmode_-_blindingly_white_blocks.2C_dark_text_on_dark_background

Please use [/r/RESIssues](https://www.reddit.com/r/RESissues/) in the future, or at least [search the repo issues](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues?q=is%3Aissue+night+mode+is%3Aclosed) before opening another one.
