### ISSUE TITLE
Can RES (for Chrome) use an "event page" instead of a persistent "background page"?

### ISSUE THREAD

**Issue by denilsonsa** [honestbleeps/Reddit-Enhancement-Suite#2651]
Some time ago, Chrome introduced *Event pages*, that behave just like *Background pages*, but unload automatically when they are not needed.

https://developer.chrome.com/extensions/event_pages

I quickly looked at [`background.js`](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/Chrome/background.js) and [`manifest.json`](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/Chrome/manifest.json), and I see nothing obvious that would require the page to be persistent, so I think it will be trivial to convert it to an "event page". Of course, I might have missed something. ;)

**Comment by erikdesjardins** [comment]
Short answer: No.

Long answer: There are a few things that make this infeasible.

First, RES uses the background page for some in-memory caching - and as far as I'm aware, there isn't a trivial way to persist it.
`localStorage` isn't an option because RES already uses it (it has limited capacity), and neither is `chrome.storage` because we'd have to add another permission (which disables RES with a "RES needs more permissions" dialog that scares users).

Second, it's not worth the performance loss, period.

On my machine, event pages take 100-200ms to wake up (and it's no slouch). Since RES has to load all of its options from the background page before it can do anything, this delay would be very noticeable.

**Comment by honestbleeps** [comment]
Agree with @erikdesjardins here... it's a good suggestion on its surface, @denilsonsa , and we appreciate it! We're always looking to make RES more efficient.  In this case, seems like it doesn't make sense to make the switch though. Thank you for the suggestion!
