### ISSUE TITLE
Turning off styleTweaks visitedStyle doesn't actually turn it off

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2654]
https://www.reddit.com/r/RESissues/comments/41ew99/bug_link_style_almost_the_same_as_text_style/

Looks like we add [alternate CSS](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/9d834dcb2656ec7c42e2622b1874eed7f0c7958d/lib/modules/styleTweaks.js#L216) for when it's off, but it's a bit overzealous.

**Comment by githue** [comment]
Yes, I made a PR about this but it has problems. #2424

The idea with that PR was: when the module is enabled, make all `.md` visited links purple. If disabled, only make visited *image* links purple. The latter is done to make sure a separate option "markVisited" works for inline images.

The problem is no one's asking for sidebar links to have a visited style, and that PR would 'break' a lot of custom themes, so it's probably better to exclude the sidebar. The other thing is the dirty `[name]` selector, but why add a visited style for inline images anyway? Images in link titles should have a visited style regardless, afaik.
