### ISSUE TITLE
Nightmode FOUC seems to be more frequent

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#2704]
Not sure if this is just an isolated issue with my machine, but I seem to be seeing the FOUC of the bright background before night mode kicks in a lot more frequently. Anyone else with the same issue?

Also, slightly unrelated, but we should move the white link CSS into our actual stylesheets to prevent that momentary flash of color.

**Comment by andytuba** [comment]
With 4.6.0 released, 4.6.1, or master?

Thanks for reminder to migrate that CSS.

**Comment by mc10** [comment]
4.6.0 released; haven't tested with 4.6.1 yet, but will do so soon.

**Comment by Fyren** [comment]
I brought this up on r/RESIssues a while back: https://www.reddit.com/r/RESissues/comments/3yz31j/bug_using_firefox_nightly_123115_and_the_latest/

This is still happening for me using both master and release/4.6.1 builds I made just now on today's nightly Firefox.  It's been happening on either every page load or nearly every page load since I my Reddit post.

**Comment by Fyren** [comment]
Other users have reported this happens to them with 4.6.0 even on the current Firefox release version (45, released yesterday): https://www.reddit.com/r/RESissues/comments/49g0b9/bug_firefox_on_mac_nightmode_bug/

**Comment by mc10** [comment]
Doesn't seem to be a problem anymore on 4.6.1; gonna close unless reproducible.
