### ISSUE TITLE
Adapt to reddit's new expando icon

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2738]
It'd be nice if we could roll with the new design and keep our distinction between expando types, but there's not too many pixels to work with.
Otherwise we use reddit's icon (technically a loss of functionality) or clobber their CSS and keep what we have now.

I'm sorta thinking we could replace the `<>` on collapsed expandos with a small icon for each type, and keep the `><` for all types of expanded expandos. (@githue any ideas?)

![image](https://cloud.githubusercontent.com/assets/7673145/13375313/c1a4c3ac-dd69-11e5-9253-7f9b551abc03.png)![image](https://cloud.githubusercontent.com/assets/7673145/13375459/09a5dc32-dd6e-11e5-96d7-b44e9b06a428.png)

(I don't know if the big ones are used anywhere)

**Comment by andytuba** [comment]
In the short term, I'm probably thinking clobber their CSS and keep what they have now. New icons based on reddit's style with badges would be neat.

I suspect the bigger ones are just for retina.

**Comment by andytuba** [comment]
> <githue
> it's probably a good opportunity to use high-res icons too, with background-size
>  <erikdesjardins>
> sounds good to me

**Comment by andytuba** [comment]
> @githue
> I agree with erikdesjardins' idea with the specific icon when non expanded, and the broken plus sign when expanded

> @andytuba
> +1

**Comment by githue** [comment]
I found that the new expando style doesn't mesh well with the existing RES icons, the new default glyph is very simple and stylized which doesn't match the RES style. Furthermore, the gray background offers little contrast for the details to show through. When I placed the RES icons in the light gray circles they were difficult to distinguish among their surroundings.

Since the +/- symbols are gone we can use the entire circle shape and play with negative space, giving each icon a more distinct profile. If you want people to recognize different media types at a glance this is essential.

Here's my redesign:
![sprite-expando-circles-lt](https://cloud.githubusercontent.com/assets/7245595/13546000/a3a2c10c-e2ea-11e5-92f7-700e49e73f43.png)

And here's an animation:
![expandos-circular-02](https://cloud.githubusercontent.com/assets/7245595/13546087/75e76426-e2ee-11e5-8598-bf1a505099a1.gif)

CSS (for testing only): http://pastebin.com/LE3u0pTK

Further notes:

* There's a bug in 4.6.0 where the 'collapsed' class doesn't get removed on first click, I'll make a PR for that shortly.
* The CSS snippet linked above includes a new method for styling NSFW expandos, it uses mix-blend-mode which can be used in subreddit stylesheets.
* I'm iffy about making a high-res version because it would break even more themes.

**Comment by thybag** [comment]
Really liking the look of those new buttons :+1:

**Comment by erikdesjardins** [comment]
:+1:

I did immediately think "refresh" for the gifv icon, but I'm sure it'll be fine once I get used to it.

> mix-blend-mode

Nice! If that also lets you make nightmode NSFW expandos red again, we can close #2630.

>I'm iffy about making a high-res version because it would break even more themes.

Makes sense.

**Comment by githue** [comment]
The gifv icon could be a closed circle minus the arrow. I thought it might be too cryptic, but it could work.

**Comment by githue** [comment]
Nightmode version added:

![sprite-expando-circles-nm](https://cloud.githubusercontent.com/assets/7245595/13834327/e7ecccb0-ec39-11e5-8ed1-ff3f41e56733.png)

**Comment by andytuba** [comment]
Spritesheet looks great! I like the "restart/loop" icon for gifv.

**Comment by andytuba** [comment]
Hmm, can we select just people who are seeing the new reddit expandos?  I'd like to maintain a consistent experience with the expando update rollout.

**Comment by githue** [comment]
I suppose we could beat them to the punch with 4.6.2, presuming they don't plan on changing the design.

**Comment by ZakariaRidouh** [comment]
These new icons seem really cool! Are they going to make it into the 4.6.2 release?

**Comment by andytuba** [comment]
@ZakariaRidouh I'm hoping to get them pretty soon.

fyi v4.6.2 at the moment actually means "hotfixed via external CSS and then add into whatever's the next release".

**Comment by githue** [comment]
If someone could find the new expando-button CSS from reddit.com and paste it all into a pastebin that would be great. I briefly searched the codebase and didn't find anything.

**Comment by erikdesjardins** [comment]
#3415
