### ISSUE TITLE
Orangered badge not showing on tab favicon

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2855]
Limitation of Edge?

**Comment by BenMcGarry** [comment]
Believed to be an Edge limitation at this stage, awaiting confirmation on this.

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/orangered.js#L153

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/vendor/favico.js
http://lab.ejci.net/favico.js/
https://github.com/ejci/favico.js

**Comment by andytuba** [comment]
We might should upgrade to 0.3.10. Current copy is 0.3.5.

**Comment by erikdesjardins** [comment]
The favicon isn't working because Edge doesn't support base64 favicon URIs.

For example, try running [this snippet](https://gist.githubusercontent.com/erikdesjardins/5258a215fae065aa441cf2670de898f2/raw/eb4d33b0a23dc139acd8115b791aed23d3e7df4d/bacon_of_favicon.js) in the console in Chrome or Firefox vs Edge.

**Comment by BenMcGarry** [comment]
Issue raised: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7480412/
