### ISSUE TITLE
Use Git LFS for large image files

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#2930]
To avoid cloning taking too long, perhaps we should store the logo files onto [Git LFS](https://git-lfs.github.com/).

**Comment by Ajedi32** [comment]
Note that this won't actually reduce the size of the existing repository (unless of course you rewrite the entire commit history), but it might prevent it from growing more in the future.

Also, is this really becoming a significant problem? Even the largest version of the logo is only 8.5 KB: https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/icon128.png

**Comment by mc10** [comment]
That [EPS file](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/assets/RESuppercase.eps) is a good 6.67 MB. Since it's one commit rewriting history might not be too bad, but it'll still be annoying to do.

**Comment by Ajedi32** [comment]
Ah. Yeah, I see what you mean. 6 MB isn't horrible, but maybe big enough to be worth using LFS.

If you're going to rewrite history I'd suggest doing it ASAP, since the longer that commit exists the more people will be basing stuff on it and the more annoying it's going to be to fix. (Maybe just remove the commit entirely for now then work out the best way to add it back in later?)

Honestly though I'm still not sure its worth using LFS just for that one 7 MB file, unless there are going to be frequent revisions to it.

**Comment by andytuba** [comment]
That file will be joined by an .ai, both of which probably will rarely change.

**Comment by mc10** [comment]
This has been unnecessary for a while since we have https://github.com/Reddit-Enhancement-Suite/assets.
