### ISSUE TITLE
Firefox 48 will change the signature of nsICookieManager::remove() again

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3052]
https://www.reddit.com/r/RESissues/comments/4mo20g/bug_user_account_switcher_doesnt_work_in_firefox/

https://bugzilla.mozilla.org/show_bug.cgi?id=1259169

AFAICT, the fix isn't backwards-compatible.

related: #2779

**Comment by xenithorb** [comment]
Ah, yes. I've been seeing this in Firefox Developer Edition, 48.0a2 and I was wondering what happened. Came here to file the ticket. Glad to see it was already reported.

**Comment by esanchma** [comment]
Aurora user here. As a temporary workaround, reverting #2779 makes everything work again for me.

**Comment by Torvin** [comment]
Reverting 34a323b would work, but will be broken again in a couple of FF versions since it is supposed to be a [temporary fix, as stated in the linked bugzilla entry](https://bugzilla.mozilla.org/show_bug.cgi?id=1259169).

The proper approach is to read the cookie first, take its originAttributes and pass it as the last parameter (instead of the second `false`).

**Comment by Torvin** [comment]
The bigger problem, though, is that this change was made to implement [contextual identity](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers). The idea is to allow users to log in to the same website using different usernames in different tabs. And RES is not quite ready to support this change - it assumes that all opened Reddit tabs are logged in under the same credentials. You can test this already by enabling `privacy.userContext.enabled` in `about:config`.
