### ISSUE TITLE
Overly-Generic Selector Causes Browser Interop Issues

### ISSUE THREAD

**Issue by jonathansampson** [honestbleeps/Reddit-Enhancement-Suite#3173]
```js
$('.submit-page #title-field .title').prepend(
    $('<span class="RESCharCounter" title="character limit: 0/300">0/300</span>')
);
```
This selector, found in [lib/modules/commentTools.js#L576](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/9e80b5731ad37a527dc5179fbc1944a334426bda/lib/modules/commentTools.js#L576), is overly-generic, and results in the targeting of textareas along with the expected title elements.

The prepending of ad-hoc span elements reveals an interop difference between browsers. Edge will render the span element text, while Chrome and Firefox do not render the element or its contents at all.

A reduction of this issue can be found here: https://jsfiddle.net/jonathansampson/unbu7u3t/

**Comment by gavin19** [comment]
Just as a quick addendum. This only became an issue due to reddit recently (and pointlessly) adding the `title` class to the textarea. For years it has been

    div#title-field
        span.title
        div.roundfield-content
            textarea

so there only ever was one matching element.

This change has caught out hundreds of subreddits as they employed much the same CSS as RES does. For example, head over to [/r/politics/submit](https://www.reddit.com/r/politics/submit) and type into the 'Title' field. It gets capitalised, despite their CSS only intending to target the 'title' text above the text box.
