### ISSUE TITLE
If you set in Settings|Submissions|New comment count|subscriptionLength to 0 then any subscribed thread becomed unsubscribed after you refresh the thread page(F5)

### ISSUE THREAD

**Issue by darkred** [honestbleeps/Reddit-Enhancement-Suite#3261]
Using Firefox 48 x64 (windows 10)  and RES 4.6.1 (as well as v4.7.6beta).

To reproduce:
- have in `Settings|Submissions|New comment count|subscriptionLength` set to 0 (instead of 2, by default), and press `save options`.  
Notice that its text description is: _"Automatically remove thread subscriptions in [x] days (**enter zero to keep subscriptions indefinitely**) - enter a number here only!"_
- subscribe to a thread, via clicking the `Subscribe?` button below it. Notice that it will become `Unsubcribe?`
- either: refresh the thread page twice (F5): you'll notice the 2nd time that that the thread will become unsubscribed (the buttom will become `Subscribe?` again),
- or, just visit your Dashboard (`cogwheel|My Dash board`)  
-_do not use the `Manage Subscription`link that appears after you click Subscribe, the issue won't occur in this case_ -  
you'll see that the thread initially appears in the list (appears subscribed) as expected.  
Now reload the page(F5): the thread will be removed from the list (will become unsubscribed).

**Comment by erikdesjardins** [comment]
Hmm, looks like this [has never worked](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/aae49c4c447c90fa4920877e8a74d6c494206f16/lib/modules/newCommentCount.js#L408). :sweat:

I'll change the description, because technically there's no need to subscribe forever (posts are archived and can't receive any more comments after 6 months, so 200 days is good enough).
