### ISSUE TITLE
RES does not work in Chrome 53/54

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3342]
Appears to be a result of a Chromium bug which was resolved yesterday. We are awaiting for this to hit stable branch. It might and might not work depending on Chrome ver and OS.

No known work around as of now.

**Comment by slikts** [comment]
Was this release not tested outside of Canary?

**Comment by vramana** [comment]
Can generators be transpiled and run using rengeneratorRuntime till we get a fix in chrome?

**Comment by Ajedi32** [comment]
This is the root cause of #3339 and #3344, right?

**Comment by BenMcGarry** [comment]
@Ajedi32 Yep

**Comment by Ajedi32** [comment]
Interesting to note that RES doesn't seem to be broken for me in Chrome 53.0.2785.89 m on Windows 7 with a fresh install of RES 5.0.0.1.

Is this only an issue for users who have chrome://flags/#enable-javascript-harmony enabled? Some users have reported that turning that setting off fixes the issue.

**Comment by RicardoDMelo** [comment]
Turning this flag off don't work for me. I'm on Chrome 53.0.2785.89 and Windows 10.

**Comment by larsjohnsen** [comment]
@RicardoDMelo Could you try using RES with another Windows user account? That should create a fresh Chrome profile, which may reveal that the cause is failed Chrome upgrade migration.

**Comment by erikdesjardins** [comment]
@slikts Of course it was tested in stable Chrome. I mentioned Canary in that thread cause that's where I would expect it to break.

![image](https://cloud.githubusercontent.com/assets/7673145/18211866/f849ed82-710d-11e6-8a36-2f4330ae4b8f.png)

**Comment by chevex** [comment]
I'm on Version 53.0.2785.89 (64-bit) and disabling the harmony flag fixed the issue for me.

@RicardoDMelo At the bottom of the screen chrome prompts you to click "relaunch" after disabling this flag. I missed it the first time and simply closed the tab and wondered why it was still broken. Did you perhaps miss that you needed to relaunch Chrome? Once I did that RES started working as expected.

**Comment by RicardoDMelo** [comment]
@chevex You nailed it. I missed the button too. Now it works!

**Comment by erikdesjardins** [comment]
> es6 generator functions are only enabled under that flag

Slight correction here: Chrome now supports all of ES6 (more-or-less) without that flag, including generators:

![image](https://cloud.githubusercontent.com/assets/7673145/18214727/47812894-711c-11e6-9d9c-0971c41356b4.png)

At this point, that flag enables generator optimization, tail-call optimization/syntactic tail calls, async/await (maybe), and some other experimental things. I wouldn't suggest you enable it for JS development.

**Comment by Ajedi32** [comment]
Alright, so I just talked to another user for whom turning off the flag didn't work, and it turns out he was using the dev channel of Chrome, which has tail call optimizations enabled even without the flag.

So for users affected by this issue:

1. Make sure the setting at `chrome://flags/#enable-javascript-harmony` is disabled. If it is enabled, disable it and restart your browser.
2. If you're using the dev channel of Chrome, switch to the stable or beta channels.

Doing those two steps should solve the problem. In any case, Chrome will likely fix this issue soon. It's already fixed in Canary, so it's only a matter of time before those fixes make their way into the other release channels.

**Comment by chevex** [comment]
So they aren't using a shim, they're just using stable generators and the optimization change broke them. Gotcha. Thanks for the correction @erikdesjardins.

Thanks @Ajedi32 for letting us know what you found :)

**Comment by thibault-ml** [comment]
Interestingly enough, I have two 10.11.6 machines running `54.0.2840.8 dev (64-bit)`, and RES works in one of them, but not the other! The `chrome://flags/#enable-javascript-harmony` is disabled in both.

**Comment by Ajedi32** [comment]
@thibault-ml That's really strange. Based on what I've heard so far, RES shouldn't be working on either of those computers since they're both using the dev version of Chrome. (Assuming they're both running the exact same patch.)

I believe since this problem doesn't affect the stable version of Chrome (unless you opt in to an experimental flag) and because it's already fixed on the master branch of V8, the current plan is to just wait for the upstream fix to make its way into a release. Or at least, that's my understanding of the situation.

**Comment by oscillot** [comment]
Diabling the harmony flag worked for me on 53/OSX but I had to restart chrome fully (kill all BG process too, eg Postman, Authy)

**Comment by Ajedi32** [comment]
Yep. To be clear, "Restart Chrome" in this instance means restarting all Chrome processes, not just closing the main Chrome window and reopening it. The `chrome://flags` page should provide a button that does that at the bottom of the screen after you change the setting.

**Comment by vramana** [comment]
RES working in Dev Channel (55.0.2853.0)

**Comment by BenMcGarry** [comment]
Issue appears to be resolved in upstream builds and reports of issues in browser vers have stopped. Closed.
