### ISSUE TITLE
clearPermissions option has disappeared

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3395]
https://www.reddit.com/r/RESissues/comments/518ms8/bug_clearpermissions_option_not_available/

Imo this option should stay to give users control over the permissions if they want to revoke them.

**Comment by BenMcGarry** [comment]
For future note for everyone, this was removed as denials are no longer cached.

**Comment by Ajedi32** [comment]
To elaborate on that, denials aren't cached because they no longer need to be; since the permissions dialog now only appears when you try to expand a link to a site which requires that specific permission. If you accidentally clicked deny and want RES to request permissions again, just click the expand button again.
