### ISSUE TITLE
"Show images" opens things that play sound.  It shouldn't.

### ISSUE THREAD

**Issue by Atario** [honestbleeps/Reddit-Enhancement-Suite#3422]
Examples:  YouTube, SoundCloud

**Comment by erikdesjardins** [comment]
What RES version are you using? I can't repro in RES 5.0.1:

![t](https://cloud.githubusercontent.com/assets/7673145/18418144/0cca609a-780f-11e6-9afc-07d7e41e7dc3.gif)

**Comment by Atario** [comment]
Sorry, I should have been clearer.  This is in comment pages.

Also, on further experimentation, this is for the following case:

1.  Find a comment that (a) started out collapsed when the page loaded, and (b) contains a YouTube/SoundCloud/other audio-producing link with expando
1.  Expand the comment
1.  Do "show images"
1.  Link plays

**Comment by Atario** [comment]
Oh, and yes, this is v.5.0.1.

**Comment by larsjohnsen** [comment]
I was able to reproduce this. Note that you need to scroll/resize the window after expanding the comment to have the expando completed. https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6541afb22559bb9654d5c06bed405fa30fe82e83/lib/modules/showImages.js#L449

@erikdesjardins Fixed in #3306
