### ISSUE TITLE
i18n Discussion

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3463]
So since we are moving forward with a i18n implementation its time to start discussing how we are going to do this and get the translations in. There are a few sections that need to be properly discussed before pushing on with this, this is a long term project.

**Framework:**

There are plenty of frameworks out there for i18n so we will need to decide which is best for out situation/implementation. I have used [i18next](http://i18next.com/) before and it is quite nice, but evaluation would be needed to make sure it supports out needs.

[WebExtensions i18n](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n)??

**Crowdsourced translations:**

Getting the translations will be the big part, there are plenty of crowdsourcing systems for getting translations. [Transifex](https://www.transifex.com/) is a very popular one used by reddit but is a paid service, however they appear to offer a solution for open source projects which is being looked into. However suggestions for other services should definitely be put forward for discussion.

This is just the start so this will grow overtime as people contribute and ideas start flowing. A project board has been setup for this and can be found [here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/projects/1).

**Comment by andytuba** [comment]
https://www.transifex.com/reddit-enhancement-suite/reddit-enhancement-suite/dashboard/

**Comment by erikdesjardins** [comment]
I would very strongly prefer a framework that allows us to pass in a js object (or if one doesn't exist, no framework at all), so that we can parse the (potentially huge) language files at compile time<sup>1</sup> instead of _every. single. pageload._

It looks like we could write our own backend for i18next to accomplish this, if necessary.

<sup>1: using a Webpack loader; `.properties` files are nigh trivial to parse</sup>

**Comment by erikdesjardins** [comment]
Alternatively, [`chrome.i18n`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n) exists and is supported by Chrome, Edge, and Firefox WebExtensions.

IMO that's something almost worth dropping Safari support for.

**Comment by BenMcGarry** [comment]
@erikdesjardins looks like the easiest implementation, noticed browserdetect isn't support with edge. Would be be using that or having options for users to manually select their language? (I'd prefer the latter)

**Comment by allthefoxes** [comment]
Latter. No autodetect.

**Comment by erikdesjardins** [comment]
`chrome.i18n` uses the browser's language, you can't pass in your own (I prefer this). Note that, because this is a browser API, it's the language that the user has explicitly configured, so common arguments against autodetect (fragility, etc.) don't apply.

And most importantly: we can add an option later if necessary, but we can't really go the other way and take an option away. There are also performance implications: module options are too slow, so everything would have to be special-cased.
