### ISSUE TITLE
Add SEO keywords to "update other tabs orangered"

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3525]
https://www.reddit.com/r/Enhancement/comments/57hohh/feature_request_as_great_as_the_unread_message/d8s1dm6?context=3

stick them somewhere in the description? add a new "keywords" field for search to look at?

**Comment by BenMcGarry** [comment]
I'd say new keywords field, and make search look at those keywords instead of description/module id.

**Comment by andytuba** [comment]
> instead of

or at least, weight them heavier (earlier) in the searchable text.

**Comment by mechacrab** [comment]
Can we *not* add SEO fucking keywords to *anything* - sure sounds like multi-accounts trying to pull some wild-assed CTR bullshit and can't get RES to update adequately.

"I'm logged in with 5 accounts and only a couple auto-update; please halp!!!111  Think of the SEO and migration possibilities!!11"

No thanks.  

Burn this motherfucker alive, please - I'm sick of these multi-account pricks ruining subreddits left and right and asking for (apparently they can't write them, the cocksuckers) tools to overrun and kill the things as well.

Let's not, for a change.  What the *hell* does "I have like...18 accounts and I'm getting confused because I'm posting on all of them in a 15 minute period!!!11111" offer?

Really?  

I don't want SEO, I don't want their bot accounts, I don't want them using their *browser* to run bot accounts, I don't care overly if they're using a fucking advanced trapper keeper smartphone to run their bot accounts, but I think this gives them a tool and I think they're too god-damned fucking stupid to do it.

I say no.  Bitch, if you have that many accounts, on fucking Reddit, you've got something wrong with ya.

Your call, but...no thanks for that goddamned result.

**Comment by BenMcGarry** [comment]
I think you missed the total point of this...

**Comment by andytuba** [comment]
I appreciate your concern for the health of the community, @mechacrab, but I'm trying to improve RES's options search, not cater to Google searches. A lot of r/Enhancement posts look like "how do you turn off res/reddit feature X? I searched for Y but couldn't find anything." By adding Y to searchable keywords, I hope to reduce the number of those posts.

**Comment by erikdesjardins** [comment]
We now have a keywords field so this should be simple
