### ISSUE TITLE
Sync filtered subreddits to /r/all native filtering

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3684]
If the user adds a subreddit to filtereddit subreddit or filtereddit subreddit filters a post, and the user is logged in, then push that subreddit to the /r/all native filters.  (Can this be batched?)

However, I believe there's a max of 100, so if the API returns an error, then back off for a while on this account, or attempt to add/remove from /r/all to optimize for most active subreddits.

**Comment by erikdesjardins** [comment]
Should be investigated for 5.3.x at least, if not implemented

**Comment by andytuba** [comment]
Janky workaround: visit https://www.reddit.com/r/all#res:settings/filteReddit

    $(".filtered-details input.sr-name").val($("#optionContainer-filteReddit-subreddits #tbody_subreddits input").map(function(){
    return $(this).val();
}).get().join(" ")).submit();

**Comment by andytuba** [comment]
https://www.reddit.com/r/Enhancement/comments/5fsl52/feature_request_now_that_reddit_has_subreddit/

**Comment by erikdesjardins** [comment]
Oh, did I say 5.3.x? I meant 5.1.x 😜

**Comment by Ajedi32** [comment]
Might want to change the milestone on this issue then, assuming that even matters...

**Comment by Ajedi32** [comment]
Also, might it be a good idea to also support syncing in the other direction? So if you make a change to Reddit's filters (maybe from another client), those changes show up in RES?

Might be a bit tricky to determine which direction to sync in though; we don't want to be accidentally undoing user's changes. There'd also be the question of what happens when you switch accounts, since RES filters are universal but Reddit filters are per-account.

**Comment by erikdesjardins** [comment]
Nah I left the milestone intentionally (I use them more as "before this point" rather than "at this point").

There's enough complexity in syncing reddit -> RES filters that it's not worth it for the MVP. Further I think it may just be too janky to implement, unless you have to choose only one direction to sync.

e.g. even in the simplest case when there's a filter present in RES and not in reddit, there are a bunch of possibilities that would require extra bookkeeping to reason about:
Just enabled the feature? RES -> reddit (or try to merge them?).
Remove a subreddit from reddit's filter? reddit -> RES.
Add a subreddit to RES's filter? RES -> reddit.
Switch accounts? Probably RES -> reddit, but not always.

**Comment by Ajedi32** [comment]
Yeah, I can think of a few reasonable ways to do it (like setting the sync option per-account, keeping track of which items on the blocklist were added/removed since the last sync, etc), but I think ultimately it'd probably turn out to be more trouble than it's worth.
