### ISSUE TITLE
showImags sometimes does not create expandos when using neverEndingReddit

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#3754]
I've not been able to reproduce this one. When this issue occurs, all other DOM enhancements still appears.

https://www.reddit.com/r/RESissues/comments/5h2lp3/bug/
https://www.reddit.com/r/RESissues/comments/5gvuei/bug_when_using_never_ending_reddit_and_the_show/

**Comment by erikdesjardins** [comment]
I've been able to reproduce this once when loading the second page.

There was no obvious cause: the second page was loaded normally (i.e. it wasn't a return-to-page after navigating backwards); all future pages had expandos like normal; there were no errors logged except `Could not post "pause" command to iframe` due to `contentWindow` being null [here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/9528e191a138a3522bea0d1218d776753ed0f952/lib/modules/showImages.js#L1355), but that's probably a symptom, not a cause.
