### ISSUE TITLE
When contracting then expanding the user bar with no unread messages in the inbox, a message count incorrectly appears showing 0 messages.

### ISSUE THREAD

**Issue by The6P4C** [honestbleeps/Reddit-Enhancement-Suite#3819]
**Bug seen on both:**
RES v5.2.2 + Chrome 55
RES v5.2.1+ Chrome 54

**Bug Description:**
The issue is caused by the `userbarHider` module, which overwrites the `display` CSS property of every element within the user bar when it is expanded (within the `toggleUserbarElementsDisplay`).

This could be fixed by applying an attribute or CSS class to the `.message-count` element. Within the `toggleUserbarElementsDisplay` function, elements with this class can be easily ignored by adding another `.not()` to the existing selector.

I have written a fix for this issue with the above technique (an attribute `res-do-not-expand` on the `.message-count` element), but it can easily be switched from a property to a CSS class if that is more preferable. If there's an even better solution, I'm happy to implement it.

[Screenshot](https://i.imgur.com/xPtBpsP.png)

**Threads on /r/RESIssues:**
https://www.reddit.com/r/RESissues/comments/5h7xvh/bug_tiny_issue_when_i_close_and_reopen_the_user/
https://www.reddit.com/r/RESissues/comments/5jqgjf/when_contracting_then_expanding_the_user_bar_with/

**Comment by andytuba** [comment]
I thought somebody had already started a PR to fix this, but here are my thoughts on how this should be implemented:

1. Mark [`userbarHider.options.userbarState`](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/1b1e2e31fb77428f983d7a23d5f73bfe8bdd0668/lib/modules/userbarHider.js#L17) as a body class. 
1. Add css   to hide everything in the user bar except the button itself when `body.res-userbarHider-userbarState- hidden` 
1. Clicking the user bar hide button only changes the option value and updates the body class, instead of touching the elements directly.

**Comment by erikdesjardins** [comment]
Possibly #3128

**Comment by The6P4C** [comment]
It pretty much is. Going to close this then.
