### ISSUE TITLE
Don't collapse comments which can't be uncollapsed

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3930]
i.e. make sure the collapse button is visible. Particularly in inbox

Comment Hide Persistor, keyboardnav "toggle comment"

https://www.reddit.com/r/RESissues/comments/5q1dm4/i_accidentally_pressed_some_buttons_and_now_the/dcw9wmy/

**Comment by erikdesjardins** [comment]
I don't think we should disable the keyboard shortcut; I imagine a few people use it when navigating their inboxes.

The real problem is with commentHidePersistor anyways, since it turns an "I accidentally pressed something" problem<sup>*</sup> into "I accidentally pressed something _and when I refresh it won't go away_".

<sup>* Which is fine to have IMO; if you often press random keys by accident you should just disable keynav.</sup>
