### ISSUE TITLE
Tumblr expando image links need an href

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#4111]
Test: https://www.reddit.com/r/restests/comments/5yut9y/tumblr_expando_image_should_link_to_tumblr_post/

Example: https://www.reddit.com/r/help/comments/5yuc0g/image_links_to_tumblr_redirect_back_to_reddit/

<img width="1440" alt="screen shot 2017-03-11 at 12 46 49 pm" src="https://cloud.githubusercontent.com/assets/455632/23826785/07a45688-0659-11e7-8c10-35d0c8f1ed7a.png">

**Comment by BenMcGarry** [comment]
Direct tumblr images not affected, only albums.

**Comment by erikdesjardins** [comment]
Seems to be because the default href [is applied here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/8f3b920643b8072f56538f2a5a5539e7871bc6fc/lib/modules/showImages.js#L1028), which doesn't affect the elements of a gallery; should probably be moved into the `generate{Image,Video}` functions
