### ISSUE TITLE
with stylesheets off in reddit prefs, use subreddit style checkbox doesn't function

### ISSUE THREAD

**Issue by honestbleeps** [honestbleeps/Reddit-Enhancement-Suite#4188]
See here: https://www.reddit.com/r/RESissues/comments/66ncqy/bug_i_turned_css_off_and_now_i_cant_get_it_to/

Repro steps: 
- visit reddit prefs, turn off "allow subreddits to show me custom themes"
- load a subreddit that has a stylesheet (e.g. r/videos), observe the style is not displayed, but "use subreddit style" may be checked.  unchecking / rechecking it does nothing.

**Comment by erikdesjardins** [comment]
Duplicates #677

This has never really worked (in 4.5.4 it resets when you refresh).

It will also be very complex to decide whether to whitelist or blacklist subreddit style, as there are three conditions:

- stylesheets disabled globally (but I'm not sure if we want to be loading everyone's prefs pages to check)
- stylesheet disabled for the current sub via gold (but we need to know before the body [and that checkbox] is parsed to avoid FOUC)
- on a subreddit page that doesn't get subreddit style (like `/about/` pages)

...so I'm not prioritizing that issue because it'll take a lot of consideration. Personally I'm not sure if it's even worth it; the logic for the current blacklist + nightmode whitelist is already complex enough.

Not to mention that CSS is going away, and depending on how it's replaced, we may not be able to easily disable the new subreddit "style".
