### ISSUE TITLE
Strikethrough and italic formatting of links falls through to expando contents

### ISSUE THREAD

**Issue by olihawes** [honestbleeps/Reddit-Enhancement-Suite#4199]
- My browser (copy from https://www.whatismybrowser.com): Chrome 57 on Windows 10
- My RES version: v5.4.3
- Am I in reddit beta (yes/no): Yes

If a link to a wikipedia article is italicised or struck through, all the body text in the expando will also have that formatting.

Eg, `~~[Struckthrough](https://en.wikipedia.org/wiki/Software_bug)~~` will produce:

![image](https://cloud.githubusercontent.com/assets/3943913/25487440/25df45c2-2b5c-11e7-998d-929905235a82.png)

and `*[Italicised](https://en.wikipedia.org/wiki/Software_bug)*` will produce:

![image](https://cloud.githubusercontent.com/assets/3943913/25487502/503ef628-2b5c-11e7-8156-3986b08f9114.png)

This does not occur if the formatting is entirely contained in the link text, as in `[~~Internal strikethrough~~](https://en.wikipedia.org/wiki/Software_bug)`, and does not appear to occur for bold (**), superscript (^) or headlined (#) links.

*Edit:* On further investigation, formatting appears to fall through to the contents of any expando, such as flickr & deviantart titles and imgur album text.

**Comment by mc10** [comment]
I don't think this is easily solvable until [`all: revert`](https://developer.mozilla.org/en-US/docs/Web/CSS/all) is implemented by browsers, as the expando is just an inline element in the post/comment, so the expando will be wrapped with `<em></em>` elements. Simply overriding the `<em>` styling could break any italics within the expando, which would also be undesirable. Since there's an easy fix to this most of the time (just apply the styles within the link text), I'd say it's probably not worth to fix at the moment.

**Comment by olihawes** [comment]
I think we're definitely stuffed on the strikethrough, but applying `font-style: normal;` to `.res-expando-box` seems to sort the `<em>` while still allowing italicisation from source articles:
![image](https://cloud.githubusercontent.com/assets/3943913/25495730/3866f2de-2b76-11e7-857d-54ea1a657cc4.png)

**Comment by mc10** [comment]
That makes sense. Any other styles you can think of besides bold, italics, and strikethrough?

**Comment by olihawes** [comment]
Not that I've noticed, no other markdown formatting seems to fall through at all.
