### ISSUE TITLE
Single Click Opener placing tabs in the wrong location

### ISSUE THREAD

**Issue by goofydylan8** [honestbleeps/Reddit-Enhancement-Suite#4230]
- My browser (copy from https://www.whatismybrowser.com): Firefox 54 on Windows 10
- My RES version: 5.6.1
- Am I in reddit beta (yes/no): No

*What's the problem?*
"Single Click Opener" now opens the link and comments in two tabs next to my current tab, instead of at the end. I have browser.tabs.insertRelatedAfterCurrent to false which normally results in any new tab opening at the far right of any open tabs. 

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

https://www.reddit.com/r/RESissues/comments/69r274/res_560_lc_lc_doesnt_respect_tab_opening_location/
https://www.reddit.com/r/Enhancement/comments/69x8nc/new_behaviour_for_single_click_opener/
https://www.reddit.com/r/RESissues/comments/6a9hmr/single_click_opener_putting_tabs_in_the_wrong_spot/

*What other browser extensions are installed?*
Add-On Compatibility Reporter
Bulk Media Downloader
Checker Plus for Gmail
F.B. Purity
Forecastfox (fix version)
FrankerFaceZ
Google Search link fix
Greasemonkey
Image Search for Google
NativeShot
Nightly Tester Tools
OpenDownload2
Restart
S3.Google Translator
Stylish
Tab Mix Plus
uBlock Origin
Undo Close Tab
Youtube Plus

**Comment by erikdesjardins** [comment]
The crux of the issue is that tabs opened by WebExtensions don't obey the `insertRelatedAfterCurrent` preference. So to keep the default behaviour (opening tabs next to the current one), we explicitly open them next to the current one. When Firefox [supports](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create#Browser_compatibility) `openerTabId` then this will probably work correctly.
