### ISSUE TITLE
Can't hide subreddit style checkbox or toolbar button

### ISSUE THREAD

**Issue by dtfinch** [honestbleeps/Reddit-Enhancement-Suite#4262]
- My browser: Firefox 53 on Windows 7
- My RES version: 5.6.4
- Am I in reddit beta (yes/no): No

*What's the problem?*

Neither the subreddit style toolbar button, nor the Use "subreddit style" checkbox respond to settings. "subredditStyleBrowserToolbarButton" is off, and "styleTweaks" is off, but both still appear. The checkbox is on all pages (duplicating Reddit's own "Show this subreddit's theme"), and the toolbar button is on pages where I've previously toggled the style off.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
A similar bug specific to the toolbar button was reported for 5.6.0, and a mod responded that it was fixed, but I still experience the bug. https://www.reddit.com/r/RESissues/comments/69n6ub/subreddit_css_toolbar_button_cant_be_properly/

*What other browser extensions are installed?*
Stylish (reddit smaller (normal) font size fix), Click to Play per-element, YesScript

**Comment by erikdesjardins** [comment]
Happens when Style Tweaks is disabled and Night Mode (the module) is not disabled

**Comment by dtfinch** [comment]
My Night Mode module (both nightMode and nightModeOn) was/is disabled.

**Comment by erikdesjardins** [comment]
Ah, I see that as well

**Comment by jplatte** [comment]
This is especially annoying when using a dark theme, because the checkbox and the area around it won't be styled. Plus it's redundant if you have reddit gold, which lets you do the same thing.
![page-shot-2017-7-15 technology](https://user-images.githubusercontent.com/951129/28242876-ea875cfe-69b7-11e7-9c1f-ff6af7e9b9fb.png)

**Comment by jplatte** [comment]
@erikdesjardins What would the desired solution here be? I'd be happy to try to write a fix for this, but I'm not sure under which conditions the checkbox should (not) be shown. Or if it should be a setting, where it would go. Can't really go on any of the appearance settings because people might have them disabled.

**Comment by erikdesjardins** [comment]
@jplatte #4341 should fix your issue
