### ISSUE TITLE
Run backups on background page

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#4309]
It's too easy to open a new tab and then quickly close it before we get a response, leading to spurious restores. ~~This is impossible to combat on a foreground page.~~

**Comment by corylulu** [comment]
Just to be sure, the backups are still be triggered by the page load though, just sent to the background. Correct? Otherwise, if two machines are left on, they'll constantly back-up over each other. 

Also, would be handy to save a marker (like an ip address) to be saved alongside a backup to indicate which machine the backup originated from. That was the automatic restore can know to ignore backups from the same machine when doing an automatic restore. 

Had that happen to me yesterday and not sure why. It wanted to restore to a backup made the prior day. It was the only machine setup for auto backups, which case, should never need to restore automatically. 

Also, I kept getting a prompt to restore to that point even after dismissing it. I'd think that dismissing a restore should persist, rename that restore point to `res-storage-conflict-<origin-ip>.json`, and then do an auto backup.

**Comment by erikdesjardins** [comment]
Yes, it will still only run on pageload.

Storing some machine-specific id would only mask the inconsistency, it wouldn't solve the actual problem.\* To be clear(er), by "spurious restores" I meant the issue you describe.

We're not going to offer conflict resolution, even manually (at least not for the initial release), but it should take you to the options page so you can turn it off or overwrite the backup.

\*: it would work, mostly, but a timestamp is already enough information to know whether the current machine made the last backup...if it didn't have bugs, hence this issue
