### ISSUE TITLE
Naver's WHALE browser, compatibility issues

### ISSUE THREAD

**Issue by Kusaha** [honestbleeps/Reddit-Enhancement-Suite#4383]
Recently the Korean technology giant released it's chromium based browser for English users as well, called [WHALE](http://whale.naver.com/en/) so I gave it a try and it's a pretty good browser, but even though it supports chrome extensions RES doesn't seem to be compatible.
![2017-08-24_02-39-02_whale](https://user-images.githubusercontent.com/7066695/29644318-755537da-8875-11e7-96f1-a8dead74d69e.jpg)

Sorry that I can't provide more information about the issue, but I'm not an expert in these thing, the last think I can provide that may be some help is the link to the  [Whale extension store](https://store.whale.naver.com/)

Edit: I'm using several other chrome extensions without any compatibility issues.

**Comment by erikdesjardins** [comment]
It looks like Whale refuses to run any extensions that have optional permissions (such as RES). I'm not sure why though, cause they'd have to explicitly disable that functionality. 😕 

Closing as this is not due to a defect in RES ([and we don't guarantee support for non-mainstream browsers / forks](https://www.reddit.com/r/enhancement/wiki/support#wiki_palemoon_and_other_firefox_.2F_chrome_forks)).
