### ISSUE TITLE
What do we need Python for?

### ISSUE THREAD

**Issue by wojtekmaj** [honestbleeps/Reddit-Enhancement-Suite#4554]
Hey,
it seems to me that the only places we use Python in RES nowadays is to print its version number (!) before installing. Experimentally, I removed it from preinstall script being too lazy to go to Python page and install it, and nothing seemed to fail. Am I missing an elephant in the room or we could remove Python from prerequisites, making it easier for others to contribute?

**Comment by mc10** [comment]
I believe some dependencies require [node-gyp](https://github.com/nodejs/node-gyp), which requires Python 2 to be installed, for their build process.

**Comment by erikdesjardins** [comment]
Yes, node-sass is a native module and so must depend on node-gyp. We plan to switch to [dart-sass](https://github.com/sass/dart-sass) once enough of it is implemented for it to work.

I'm guessing that you have a `/usr/bin/python2.7` binary, but not one for `python`, so that's why the preinstall script fails. Given the number of different possibilities (`python`, `python2`, `python2.7`) we should probably just remove it from the preinstall script.
