### ISSUE TITLE
Steamcommunity module has intermittent issues showing expandos.

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#4583]
See post: https://www.reddit.com/r/restests/comments/7ijadt/expando_test_isolated/

The module is random with expanding some steam community links. Both links in the above post are valid however only one is rendered with a console error returned for the unrendered image,

```
TypeError: Cannot read property 'endsWith' of undefined
    at src.some.ext (chrome-extension://flhpapomijliefifkkeepedibpmibbpo/foreground.entry.js:40063)
    at Array.some (<anonymous>)
    at Host.handleLink (chrome-extension://flhpapomijliefifkkeepedibpmibbpo/foreground.entry.js:40063)
    at <anonymous>
```

It appears that request that goes out for the failed image does not return correct data.

Failed Response:
```
{
	"response": {
		"result": 1,
		"resultcount": 1,
		"publishedfiledetails": [
			{
				"publishedfileid": "622528032",
				"result": 9
			}
		]
		
	}
}
```

**Comment by pll33** [comment]
I reached out to Steamworks Support for help. It seems like it's an issue with that particular API endpoint. 

I'm thinking it might be an issue highly dependent on the game since it seems to work fine with screenshots from Valve games like TF2, Portal 2, CS:GO, and DOTA 2 though it didn't work with Half Life 2 or Portal 1. All other non-Valve games I tried didn't work including PUBG, Borderlands TPS/2, and Fallout 4.

**Comment by pll33** [comment]
Response from Steamworks Support

> Hello,    
>
> This will happen when the owner of the file has made their Community profile private. The owner of 622527263 is currently set to private, so you won't be able to get the details from the API. 
>
> Thanks	
> Jason

**Comment by erikdesjardins** [comment]
Thanks for the investigation!

In that case we should just throw an error when we get a response like that
