### ISSUE TITLE
On self posts, apply user tagger "highlight" to u/ mentioned in post text

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#4822]
This accommodates group AMAs where contributors are identified in the self-text, or AMAs where OP is actually the publicist.

This also makes r/drama posts hilarious.

**Comment by IAmBullsaw** [comment]
Take this with a grain of salt  since I have no connection to this repo - except via Hacktober ^^, but I think it means that:

When making a self posts on reddit, it's always made by one user.  When this user posts answers to other users questions, the username is highlightet to more easily discern the user who made the AMA post.

However, there's often AMA's where a whole team answers questions. Still one user can make the original post, but it's often that the other team members are presented with their usernames in the self posts post text. 

I think it's these users who are supposed to be highlighted in the same way the original poster is. Makes sense?

**Comment by andytuba** [comment]
@iambullsaw is right on the mark, thanks for helping clarify.


Example:
https://www.reddit.com/r/NintendoSwitch/comments/7tuubc/hey_were_the_dev_team_behind_celeste_ask_us/?utm_source=reddit-android

**Comment by andytuba** [comment]
@jackneus, I imagine that inside the User Highlight module, in the "go" function, you could add some code to find username links in the self post, and then call the "highlight user" function. 

It's also good to add an option to disable this behavior.

**Comment by Brcrwilliams** [comment]
I have created a WIP pull request for this feature. Feedback welcome. There are a few things that I am not sure how to do (locales?), which is described in the PR if anyone is able to offer advice.

**Comment by sahilrawat001** [comment]
I want to work on this issue can anyone tell me steps to do for it?

**Comment by Brcrwilliams** [comment]
@sahilrawat001 This has already been implemented in https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4866,  but we forgot to close the issue when the PR was merged. 

@andytuba Would you mind closing this issue please?

**Comment by andytuba** [comment]
Thanks for helping with the book keeping!
