### ISSUE TITLE
How to install old versions in Firefox?

### ISSUE THREAD

**Issue by ooker777** [honestbleeps/Reddit-Enhancement-Suite#5018]
([I asked on r/RESissues first](https://www.reddit.com/r/RESissues/comments/adw2el/how_to_install_old_res_version_on_firefox/?st=jqooinas&sh=c80f5bb1) but no one answers) 

For various reasons, I have to use Firefox 52. The latest version that compatible with it is 5.6.5, but it doesn't work. I intend to install [an older version](https://github.com/honestbleeps/Reddit-Enhancement-Suite/releases?after=v5.6.4), but after downloading it there is no .xpi file to manually install them. Do you know how to install it?

Also, as I know, WebExtension addons can still be installed in this version. Why can't newer versions be installed?

**Comment by mc10** [comment]
You should be able to [find old versions on the AMO website](https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/versions/); I think you can disable auto-updating if necessary.

We generally bump the minimum version required if there's a feature that's only supported on a later version. We most recently [bumped Firefox to v57 and later](https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/d840ad1c6139238659f5b6c9d43f158000d05c01) because `openerTabId` was only added in that version.

**Comment by mc10** [comment]
In that case, I believe [5.12.6](https://github.com/honestbleeps/Reddit-Enhancement-Suite/releases/tag/v5.12.6) is probably the latest version that's compatible with Firefox 52.

**Comment by mc10** [comment]
You're in a tough situation that we can't really support; any version as old as 5.6.x probably has a bunch of bugs that were fixed in later versions, and any more recent versions depend on features that don't exist in your browser. You might be able to get away with installing one of these incompatible versions and disabling the version check, but there's no guarantee that it'll work.

**Comment by ooker777** [comment]
I try to download 5.6.3 and rename the extension from zip to xpi, but FF says it appears to be corrupted.  Do you have any idea?

**Comment by ooker777** [comment]
It doesn't work at all
