### ISSUE TITLE
RES is breaking dark themed subreddits with white color comment highlights

### ISSUE THREAD

**Issue by ap-Di0** [honestbleeps/Reddit-Enhancement-Suite#5135]
A lot of users on our subreddit are randomly getting white highlights on their comments. This is a major issue when our subreddit is mainly dark themed. The problem is it happens seemingly to random users. Some have RES but don't experience it, others have RES as well but they get the issue. 

This feature is completely breaking the browsing experience on our subreddit. 
https://imgur.com/a/2AI933c

Has anyone on the project considered exceptions for dark themed subreddits? Is there a way to opt out our subreddit from this comment highlighting feature? 

I would appreciate any help on this.

**Comment by honestbleeps** [comment]
this is a feature called "commentBoxes", and you can style to accommodate the comment highlighting. it takes just a little extra work.

the reason we do not put exceptions in for this is because unfortunately way too many moderators of subreddits write messy, even terrible CSS (understandable, considering you don't need to be a web developer to be a subreddit moderator).

The point of the commentBoxes feature is to alternate colors at each depth to make the site more readable.  Allowing subreddit moderators to "turn this off" means prioritizing subreddit moderators preferences over individual users' preferences, which isn't really the way we prefer to go. Much of RES is about empowering the individual user to customize reddit the way they want.

So, with all that philosophical ranting out of the way - here's an example of some CSS you could add to your subreddit. Yes, it's a little ugly. Unfortunately this is by necessity.

```
// even depth comments
.res-commentBoxes .comment .comment,
.res-commentBoxes .comment .comment .comment .comment,
.res-commentBoxes .comment .comment .comment .comment .comment .comment,
.res-commentBoxes .comment .comment .comment .comment .comment .comment .comment .comment,
.res-commentBoxes .comment .comment .comment .comment .comment .comment .comment .comment .comment .comment { background-color: #34333c !important }

// odd depth comments
.res-commentBoxes .comment ,
.res-commentBoxes .comment .comment .comment,
.res-commentBoxes .comment .comment .comment .comment .comment,
.res-commentBoxes .comment .comment .comment .comment .comment .comment .comment,
.res-commentBoxes .comment .comment .comment .comment .comment .comment .comment .comment .comment { background-color: #28272e !important }
```

**Comment by ap-Di0** [comment]
The point of having a single toggle is to avoid messy CSS like the one you've provided above in order to work around this feature. As a moderator, I'm not forcing anything on the user, its a compromise to avoid recommending they turn off RES, and a way for my CSS and RES to work together better. 

I've heard of this issue on so many dark themed subreddits, there must be something better you can do.

**Comment by honestbleeps** [comment]
I'm not sure if you deleted your comment or what, but I don't see it anymore, so I'll quote it...

> The point of having a single toggle is to avoid messy CSS like the one you've provided above in order to work around this feature. As a moderator, I'm not forcing anything on the user, its a compromise to avoid recommending they turn off RES, and a way for my CSS and RES to work together better.
>
> I've heard of this issue on so many dark themed subreddits, there must be something better you can do.

The point of the feature, which is *optional*, is for the user to declare a preference for seeing alternating colored comment depths.

This type of CSS is literally the only possible way to accomplish it.

If your preference as a subreddit moderator is to not style for it, then users can disable your stylesheet.  You shouldn't put that you're fully RES compatible if you're not.

If your preference as a moderator is to style for it, Ive given you some code you can simply copy/paste.

When you say "there's got to be something better you can do" - we haven't found any other solution.  If you've got a suggestion for how to BOTH accommodate the user's preference AND have simpler CSS, I'm all ears... but it sounds like what you're asking for is "just don't output CSS that alternates the comment background colors" and that's not what our users want. That's the very point of the *optional* `commentBoxes` feature of RES.
