### ISSUE TITLE
Firefox 68.x ESR is not supported

### ISSUE THREAD

**Issue by drlellinger** [honestbleeps/Reddit-Enhancement-Suite#5173]
The addon has been compatible with 68.0, 68.1, 68.2 and 68.3 in the past.
Please revert this

**Comment by DanGamingTV** [comment]
Also, this means that the addon is not compatible with the latest version of tor browser. Please fix this!

**Comment by tucznak** [comment]
Adding to this, ESR 68 just released recently, no reason to not support it anymore.

**Comment by BenMcGarry** [comment]
Due to extension APIs res uses, we require a minimum of 69 as that is the version that supports them.  As ESR does not add new features until major releases, we cannot maintain RES at that version.

**Comment by drlellinger** [comment]
Sad

**Comment by tlc** [comment]
ESR is what corporations stick on their machines on which the users don't have the permissions to get a newer version.

Not supporting ESR is like having an Ubuntu app and not supporting the latest LTS release.

**Comment by honestbleeps** [comment]
friendly reminder that RES is a volunteer run project, developed and
maintained by unpaid engineers who see a negligible (as in less than a
coffee a month these days) amount of donations or support. it's a passion
project that folks work on in their spare time when they can.

I understand that RES has gotten quite large, which makes folks think of it
as a "professional-ish product" -- but it is not trivial to support older
versions of browsers and maintain backwards compatibility going forward. It
requires:

- additional code with conditional checks, etc, to maintain backward
compatibility
- additional testing in more versions of more browsers, which isn't
something we have the staff/horsepower to maintain

We would certainly welcome a pull request from someone interested in
supporting ESR, but cannot justify doing the work on our own in order to
support a very small percentage of users.  It's a matter of prioritizing
where we spend our [free/unpaid] time.

**Comment by pmuybae** [comment]
Does anyone know the latest version that is compatible with Firefox 68?
