### ISSUE TITLE
Chrome experiencing extreme slow down…

### ISSUE THREAD

**Issue by DooMMasteR** [honestbleeps/Reddit-Enhancement-Suite#5194]
- My browser: Chrome 81 on Linux https://www.whatismybrowser.com
- My RES version: v5.18.11
- Am I in reddit beta (yes/no): no

Expandos and general browsing are experiencing extreme slow downs, it happens super suddenly, first all is fine and then an expando takes 8 seconds to load. 
This usually starts happening around post 100 sometimes less, sometimes more.  
It also happens on all my machines, be it Windows or Linux, my Laptop or my Ryzen 3800X equipped desktop with 64GB of RAM.
CPU load stays in check, which makes me wonder where the issue is?

This issue also exists with all my other extensions deacitvated.

**Comment by honestbleeps** [comment]
all RES's expandos do is add an IMG or VIDEO tag to the page unless it's a unique expando with an iframe.

it appears you're on a beta version of Chrome, and on Linux.  I'm guessing you'd likely have this same issue on the reddit redesign without RES enabled, and chrome is having an issue with memory or CPU due to a bunch of images/video being open. Could be a beta issue, or could be a linux issue, hard to say.  Unlikely to be RES, though I am not 100% ruling it out - it's just that RES doesn't really do anything but add an HTML tag to the page when you open an expando -- Chrome just renders it.

**Comment by DooMMasteR** [comment]
I am not using the redesign :-) (old Reddit in use) but yet, chrome was the issue, a later releases fixed it.
