### ISSUE TITLE
[Chrome] Google Drive backup module not recieving access token.

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#5212]
As of last night it appears that during the oauth call-back no access token is being returned from google blocking backups/restores of RES settings. G Drive API Dev console shows no major errors.

No console errors from the google network requests.

![image](https://user-images.githubusercontent.com/9434920/79970081-4ff48680-848a-11ea-95b0-40dde45ac5ac.png)

**Comment by trued02** [comment]
I have this issue as well, a few days ago I started up chrome and reddit and found all of my usertags gone, after checking to see if I had backed up to drive I got the error. This is even though google shows that RES has access to my google account since Feb 2020. I tried to restore and backup on both Old and "new" reddit, both failed.

**Comment by YenForYang** [comment]
The "No token found in response" seems to still occur when googleAccount (`googleLoginHint`) is specified. 

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/5e2630b00a5837f9a59b8fbbefd8aa4acf136953/lib/environment/foreground/auth.js#L28-L41


I looked into the value of `responseUrl` when `googleLoginHint` is specified, and it's of the form:
```
https://accounts.google.com/o/oauth2/v2/auth?...
```
which is missing the `access_token` parameter rather than expected
```
https://redditenhancementsuite.com/oauth#access_token=...
```

But the returned `responseUrl` is valid, because when I punched `responseUrl` into the chrome browser (i.e. made an additional GET request) it performs a redirect to the correct address `https://redditenhancementsuite.com/oauth#access_token=...` which contains the `access_token` desired

**Comment by ptxmac** [comment]
I'm seeing this issue on 5.22.5
