### ISSUE TITLE
some v.redd.it videos don't expand properly in the dashboard (broken again)

### ISSUE THREAD

**Issue by canDry** [honestbleeps/Reddit-Enhancement-Suite#5258]
Similar to this issue that was recently fixed/closed:  
https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/4745  
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/5244

The issue is happening again with **some** videos.

When you expand a v.reddit video in the DASHBOARD it displays a border but not the video.

eg:  https://www.reddit.com/r/virtualreality/comments/j24sqc/the_new_walking_dead_game/  
**when listed in the DASHBOARD view.

Using RES: v5.20.7

FF:  81 (and previous version)

cc: @larsjohnsen

**Comment by patricknelson** [comment]
It appears to be a 403 forbidden error but I actually think it's due to an invalid request.  In this case, it looks like for some reason the correct URL to the MP4 is being appended to the video's direct link (i.e. `https://v.redd.it/[random-string]/`), e.g. `https://v.redd.it/[random-string]/https://vcf.redd.it/[random-string]/DASH_720.mp4?Expires=[num]&Signature=[signature]` 

Here's a gif of it in action:

![2020-09-30_11-50-45](https://user-images.githubusercontent.com/4269377/94727583-cf2c9700-0313-11eb-95fe-728d3c817346.gif)

**Comment by larsjohnsen** [comment]
This issue is due RES' module for v.redd.it not expecting the videos to be hosted on another subdomain. It is however fix in the latest version (v5.20.9).

**Comment by patricknelson** [comment]
Ok, I'm still on v5.20.7. How do I update to the latest version @larsjohnsen? The web store is still showing this same old version which is 7 minor versions behind and already 11 days old. Thanks!

**Comment by larsjohnsen** [comment]
The Chrome web store is unfortunately a little slow in processing releases. It typically takes 1-3 days, so it is probably available by tomorrow.

**Comment by canDry** [comment]
> This issue is due RES' module for v.redd.it not expecting the videos to be hosted on another subdomain. It is however fix in the latest version (v5.20.9).

Thanks lars.  I see 5.20.9 just dropped 30 mins ago... will see if I can d/l, install and test.
