### ISSUE TITLE
v5.24.4 may have broke twitter picture and video embedding on old.reddit.com

### ISSUE THREAD

**Issue by MCPtz** [honestbleeps/Reddit-Enhancement-Suite#5517]
- My browser (copy from https://www.whatismybrowser.com):
  - Brave: [Version 1.64.116 Chromium: 123.0.6312.105 (Official Build) (x86_64)](https://brave.com/latest/)
- My RES version:
  - [v5.24.4](https://redditenhancementsuite.com/releases/5.24.4/)
- Am I in reddit beta (yes/no): 
  - No
  - On old.reddit.com

*What's the problem?*
The recent update with [v5.24.4](https://redditenhancementsuite.com/releases/5.24.4/) added support to expand x.com, alongside twitter.com URLs.

But in this update, when expanding twitter.com and x.com tweets containing images or pictures, neither will load:

[E.g. this tweet with a picture
](https://twitter.com/steve_hewitt/status/1782025514972008761?t=Y5WerpSqHXi-MkpSS-ZfCw&s=19)

Or [This tweet with a video](https://twitter.com/toddzolecki/status/1782096917037469783)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
I couldn't find anything via search function on github

*What other browser extensions are installed?*
uBlock 1.57.0
Brave shield set to default settings.

Example screen capture:
<img width="1091" alt="image" src="https://github.com/honestbleeps/Reddit-Enhancement-Suite/assets/6564782/bbba63b6-989c-46b6-95a8-e984d78d68b2">

**Comment by BenMcGarry** [comment]
Not a bug, this is called out here: https://www.reddit.com/r/RESissues/s/T25cId0DRY

**Comment by MCPtz** [comment]
It worked until v5.24.4 from twitter.com links.

If it's disabled for some security reason, then probably file a new security bug for the left side preview, seen below, is showing the image somehow.

If it's ok to grab the image for the preview, then it seems to me that it should show embedded pictures and maybe videos too.

In fact, right now, it was able to grab the image here on the side:
![image](https://github.com/honestbleeps/Reddit-Enhancement-Suite/assets/6564782/a7a17594-07ac-41c1-b9c4-a473a1d89975)

Expanded, no image shown:
![image](https://github.com/honestbleeps/Reddit-Enhancement-Suite/assets/6564782/2fa97866-9b3c-4b36-b826-7a97a2009791)

And if we look at it on twitter.com:
![image](https://github.com/honestbleeps/Reddit-Enhancement-Suite/assets/6564782/b011be5c-17a1-46dd-bf44-c29047dee1e1)

**Comment by BenMcGarry** [comment]
It's restricted because of Google's policy, there is nothing RES can do. The thumbnail shown is a Reddit feature not RES.

https://developer.chrome.com/docs/extensions/develop/migrate/improve-security#remove-remote-code

"In Manifest V3, all of your extension's logic must be part of the extension package. You can no longer load and execute remotely hosted files according to [Chrome Web Store policy](https://developer.chrome.com/docs/webstore/program-policies/mv3-requirements). Examples include:

- JavaScript files pulled from the developer's server.
- Any library hosted on a [CDN](https://developer.mozilla.org/docs/Glossary/CDN).
- Bundled third-party libraries that dynamically fetch remote hosted code."

**Comment by elmagio** [comment]
Was this change also made to the Firefox version? I'm experiencing the same behavior on it as I do on Chrome.

**Comment by BenMcGarry** [comment]
It's been like this on Firefox for years as they have always had the same requirement.
