### ISSUE TITLE
clicking expandod image opens in new tab?

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#924]
http://www.reddit.com/r/RESissues/comments/22snhf/bug_when_i_scale_an_image_in_expando_it_opens_the/

**Comment by larsjohnsen** [comment]
Fixed.

**Comment by erikdesjardins** [comment]
Can confirm, this happens when you drag off and back onto an image, then release the mouse, e.g.

![test](https://cloud.githubusercontent.com/assets/7673145/15658157/070653d2-2687-11e6-9068-5e4a7e6ce245.gif)

Users with slow machines can probably make this happen by dragging normally (down and to the right) and "outrunning" the resize handler.
